name: push-items

on:
  push:
    branches:
      - main
    paths:
      - "items/**"

jobs:
  docker-image:
    runs-on: ubuntu-24.04
    needs: release

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        run: |
          echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV
        working-directory: ./items

      - name: Check whether version already exists
        id: check_version
        run: |
          echo "Checking if version ${{ env.VERSION }} already exists"
          if docker manifest inspect ghcr.io/merschformann/items:${{ env.VERSION }}; then
            echo "Version ${{ env.VERSION }} already exists"
            echo "VERSION_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Version ${{ env.VERSION }} does not exist"
            echo "VERSION_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Build the items Docker image
        if: env.VERSION_EXISTS == 'false'
        run: |
          echo "Building items docker image ${{ env.VERSION }}"
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          export LATEST_TAG="ghcr.io/merschformann/items:latest"
          export VERSION_TAG="ghcr.io/merschformann/items:${{ env.VERSION }}"
          docker buildx build --platform linux/amd64,linux/arm64 --push -t $LATEST_TAG -t $VERSION_TAG -f Dockerfile ..
        working-directory: ./items
